title: NLV Modellflug Saarmund e.V.
email: info@nlvms.de
description: Modellflugverein in Saarmund
baseurl: ""
url: ""
github: [metadata]

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true
      related: true
